[theme]
primaryColor = "#4682B4"  # SteelBlue for primary accents
backgroundColor = "#ffffff"  # white background
secondaryBackgroundColor = "#E6F2FF"  # Light pastel blue for sidebars/widgets
textColor = "#2C3E50"  # Charcoal for text, ensuring good readability
font = "sans serif"  # Clean and modern font
